# Generated by Django 5.2.4 on 2025-08-03 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='euser',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='euser',
            name='user_type',
        ),
    ]
