# Generated by Django 5.2.4 on 2025-08-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_euser_full_name_remove_euser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='euser',
            name='user_image',
            field=models.ImageField(blank=True, upload_to='authentication/img/user_images'),
        ),
    ]
