# Generated by Django 5.2.4 on 2025-08-07 11:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_euser_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='euser',
            name='middle_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='middle name'),
        ),
        migrations.AddField(
            model_name='euser',
            name='mobile_number',
            field=models.CharField(max_length=16, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid international phone number (e.g. +254712345678)', regex='^\\+?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='euser',
            name='user_image',
            field=models.ImageField(blank=True, upload_to='user_images/'),
        ),
    ]
