# Generated by Django 5.2.4 on 2025-08-07 11:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_euser_middle_name_euser_mobile_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='euser',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid international phone number (e.g. +254712345678)', regex='^\\+?\\d{9,15}$')]),
        ),
    ]
