# Generated by Django 5.2.4 on 2025-08-08 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_euser_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='euser',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='euser',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='middle name'),
            preserve_default=False,
        ),
    ]
