# Generated by Django 5.2.4 on 2025-08-12 06:14

import authentication.storages_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_euser_first_name_alter_euser_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='euser',
            name='user_image',
            field=models.ImageField(blank=True, storage=authentication.storages_backends.R2UserImageStorage(), upload_to='scms_user_images/'),
        ),
    ]
